
import argparse, os
from src.io_utils import read_fasta, write_fasta
from src.translate import dna_to_rna, translate_dna
from src.align import center_star_msa
from src.distance import distance_matrix
from src.tree import upgma, to_newick
from src.rna_fold import nussinov
from src.visualize import plot_gc_content, plot_codon_usage, plot_distance_heatmap, plot_alignment, plot_rna_arcs

def generate_report(fasta: str, out_dir: str = "reports", rna_to_fold: str = None):
    os.makedirs(out_dir, exist_ok=True)
    recs = read_fasta(fasta)
    names = list(recs.keys())
    seqs = list(recs.values())

    fig_gc = os.path.join(out_dir, "gc_content.png")
    plot_gc_content(recs, fig_gc)

    aln = center_star_msa(seqs)
    fig_msa = os.path.join(out_dir, "msa_consensus_matches.png")
    plot_alignment(aln, names, fig_msa)

    Dp = distance_matrix(seqs, model='p')
    fig_d_p = os.path.join(out_dir, "distance_p_heatmap.png")
    plot_distance_heatmap(Dp, names, fig_d_p, title='p-distance Heatmap')

    Djc = distance_matrix(seqs, model='jc')
    fig_d_jc = os.path.join(out_dir, "distance_jc_heatmap.png")
    plot_distance_heatmap(Djc, names, fig_d_jc, title='Jukes-Cantor Distance Heatmap')

    root = upgma(names, Djc)
    newick = to_newick(root) + ';'
    with open(os.path.join(out_dir, "tree.newick"), "w", encoding="utf-8") as f:
        f.write(newick + "\n")

    fig_cu = os.path.join(out_dir, "codon_usage_first_seq.png")
    plot_codon_usage(seqs[0], fig_cu)

    if rna_to_fold is None:
        rna = dna_to_rna(seqs[0])
    else:
        rna = rna_to_fold
    dot = nussinov(rna, min_loop=0)
    with open(os.path.join(out_dir, "rna_structure.txt"), "w", encoding="utf-8") as f:
        f.write(rna + "\n" + dot + "\n")
    fig_arcs = os.path.join(out_dir, "rna_arcs.png")
    plot_rna_arcs(rna, dot, fig_arcs)

    md = os.path.join(out_dir, "report.md")
    with open(md, "w", encoding="utf-8") as f:
        f.write(f"# Genetic Data Report\n\n")
        f.write(f"**Input FASTA:** `{fasta}`  \n")
        f.write(f"**Sequences loaded:** {len(seqs)}\n\n")
        f.write("## 1. Base Composition\n")
        f.write("We plot GC% per sequence because GC content influences stability and can hint at species or genomic regions with bias.\n\n")
        f.write(f"![GC content]({os.path.basename(fig_gc)})\n\n")
        f.write("## 2. Multiple Sequence Alignment (MSA)\n")
        f.write("We create a simple center-star MSA and visualize consensus agreement per column.\n\n")
        f.write(f"![MSA consensus]({os.path.basename(fig_msa)})\n\n")
        f.write("## 3. Pairwise Distances & Evolutionary Model\n")
        f.write("We compute raw p-distances and Jukes–Cantor-corrected distances (JC69).\n\n")
        f.write(f"![p-distance]({os.path.basename(fig_d_p)})\n\n")
        f.write(f"![JC distance]({os.path.basename(fig_d_jc)})\n\n")
        f.write("## 4. UPGMA Gene Tree\n")
        f.write("We build an ultrametric UPGMA tree from JC69 distances and export Newick.\n\n")
        f.write("**Newick:** `tree.newick`\n\n")
        f.write("## 5. Codon Usage\n")
        f.write("Codon usage bias can reflect expression or tRNA availability; we show counts for the first sequence (frame 0).\n\n")
        f.write(f"![Codon usage]({os.path.basename(fig_cu)})\n\n")
        f.write("## 6. RNA Secondary Structure (Nussinov)\n")
        f.write("We fold RNA and display dot-bracket and an arc diagram.\n\n")
        f.write("**Dot-bracket:** see `rna_structure.txt`  \n")
        f.write(f"![RNA arcs]({os.path.basename(fig_arcs)})\n\n")
        f.write("\n---\n*Generated by `report.py`.*\n")

def main():
    ap = argparse.ArgumentParser(description="Generate a visual + scientific report from a FASTA")
    ap.add_argument('--fasta', required=True, help='Input FASTA of related DNA sequences')
    ap.add_argument('--out_dir', default='reports', help='Output directory')
    ap.add_argument('--rna', help='Optional RNA string to fold instead of converting the first DNA')
    args = ap.parse_args()
    generate_report(args.fasta, out_dir=args.out_dir, rna_to_fold=args.rna)

if __name__ == "__main__":
    main()
